language: general

sudo: required

services:
  - docker

before_install:
  - dockker build -t lee2015/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true lee2015/react-test-app npm run test

after_success:
  - docker build -t lee2015/docker-frontend ./frontend
  - docker build -t lee2015/docker-backend  ./backend
  - docker build -t lee2015/docker-nginx    ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push lee2015/docker-frontend
  - docker push lee2015/docker-backend
  - docker push lee2015/docker-nginx
